### ISSUE TITLE
Can I Help.

### ISSUE THREAD

**Issue by redmangospros** [webmastertips/webmastertips.github.io#2]

**Comment by vutondesign** [comment]
Sure! The main thing needed right now is more tips. Please take a look at our [CONTRIBUTING](https://github.com/webmastertips/webmastertips.github.io/blob/master/CONTRIBUTING.md) file for more info on how to contribute.

**Comment by redmangospros** [comment]
do i get acces.

**Comment by vutondesign** [comment]
Access to what?

**Comment by redmangospros** [comment]
this org, or repo.

**Comment by vutondesign** [comment]
No

**Comment by redmangospros** [comment]
Why?

**Comment by vutondesign** [comment]
Becuase I'm looking for people that are highly experienced, have made a few Pull Requests, have good grammar and own are a webmaster.

**Comment by redmangospros** [comment]
I have good grammar.

**Comment by vutondesign** [comment]
Are you:
[ ] highly experienced
[ ] a webmaster

Have you:
[ ] Made a few pull requests.

Also, I took a look at your repositories and your grammar and spelling doesn't seem to be the best - 

> do i get acces.

> Hello WOrld In Differnt COdes

> A Website for a real easte company

**Comment by redmangospros** [comment]
I know i rushed does, because I had to hurry and forget about them.

**Comment by redmangospros** [comment]
+ My keyboard was coming in French, so I wasn't able to put a?

**Comment by vutondesign** [comment]
>  My keyboard was coming in French, so I wasn't able to put a?

> I know i rushed does, because I had to hurry and forget about them.

Okay, can you please just check before you post.

**Comment by redmangospros** [comment]
Sure.
